-- MySQL Script generated by MySQL Workbench
-- Sun Feb 27 20:33:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jptdatabase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jptdatabase` ;

-- -----------------------------------------------------
-- Schema jptdatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jptdatabase` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `jptdatabase` ;

-- -----------------------------------------------------
-- Table `jptdatabase`.`configurations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jptdatabase`.`configurations` ;

CREATE TABLE IF NOT EXISTS `jptdatabase`.`configurations` (
  `id` INT NOT NULL,
  `hub_name` VARCHAR(30) NULL DEFAULT NULL,
  `num_nodes` INT NULL DEFAULT NULL,
  `ip_server` VARCHAR(30) NULL DEFAULT NULL,
  `port_server` INT NULL DEFAULT NULL,
  `internet` VARCHAR(30) NULL DEFAULT NULL,
  `password` VARCHAR(30) NULL DEFAULT NULL,
  `mdb_flag` INT NULL DEFAULT NULL,
  `mdb_id` INT NULL DEFAULT NULL,
  `mdb_type` INT NULL DEFAULT NULL,
  `mdb_parity` VARCHAR(30) NULL DEFAULT NULL,
  `mdb_baud` INT NULL DEFAULT NULL,
  `mdb_dbits` INT NULL DEFAULT NULL,
  `mdb_sbits` INT NULL DEFAULT NULL,
  `mdb_timeout` INT NULL DEFAULT NULL,
  `mdb_tries` INT NULL DEFAULT NULL,
  `fac_modem` VARCHAR(30) NULL DEFAULT NULL,
  `fac_radio` VARCHAR(30) NULL DEFAULT NULL,
  `fac_mdb` VARCHAR(30) NULL DEFAULT NULL,
  `sta_cld` INT NULL DEFAULT NULL,
  `mdb_input_reg` INT NULL DEFAULT NULL,
  `mdb_holding_reg` INT NULL DEFAULT NULL,
  `mdb_input_dis` INT NULL DEFAULT NULL,
  `mdb_coil_dis` INT NULL DEFAULT NULL,
  `sta_pwm` INT NULL DEFAULT NULL,
  `mdb_baud_rate` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jptdatabase`.`delayer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jptdatabase`.`delayer` ;

CREATE TABLE IF NOT EXISTS `jptdatabase`.`delayer` (
  `id` INT NOT NULL,
  `direct` VARCHAR(30) NULL DEFAULT NULL,
  `number` INT NULL DEFAULT NULL,
  `multiplier` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jptdatabase`.`indiceambiental`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jptdatabase`.`indiceambiental` ;

CREATE TABLE IF NOT EXISTS `jptdatabase`.`indiceambiental` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `temperatura` FLOAT NULL DEFAULT NULL,
  `humedad` FLOAT NULL DEFAULT NULL,
  `nivel` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jptdatabase`.`modbus_config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jptdatabase`.`modbus_config` ;

CREATE TABLE IF NOT EXISTS `jptdatabase`.`modbus_config` (
  `id` INT NOT NULL,
  `parity` TEXT NOT NULL,
  `baud_rate` INT NOT NULL,
  `data_bits` INT NOT NULL,
  `stop_bits` INT NOT NULL,
  `port` INT NULL DEFAULT NULL,
  `ip` INT NULL DEFAULT NULL,
  `ip_port` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jptdatabase`.`modbus_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jptdatabase`.`modbus_table` ;

CREATE TABLE IF NOT EXISTS `jptdatabase`.`modbus_table` (
  `id` INT NOT NULL,
  `date` TEXT NULL DEFAULT NULL,
  `data_table` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jptdatabase`.`modules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jptdatabase`.`modules` ;

CREATE TABLE IF NOT EXISTS `jptdatabase`.`modules` (
  `id` INT NOT NULL,
  `name_module` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jptdatabase`.`nodex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jptdatabase`.`nodex` ;

CREATE TABLE IF NOT EXISTS `jptdatabase`.`nodex` (
  `id` INT NOT NULL,
  `m_datetime` DATETIME NOT NULL,
  `m_device` VARCHAR(9) NOT NULL,
  `m_data` TEXT NOT NULL,
  `verify_send` VARCHAR(1) NULL DEFAULT 'F',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jptdatabase`.`sqlite_sequence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jptdatabase`.`sqlite_sequence` ;

CREATE TABLE IF NOT EXISTS `jptdatabase`.`sqlite_sequence` (
  `name` BINARY(1) NULL DEFAULT NULL,
  `seq` BINARY(1) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
